language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base qt59webengine qt59svg qt5-qmake
  - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - mkdir appdir
  - sudo make INSTALL_ROOT=appdir install ; sudo chown -R $USER appdir ; find appdir/

after_success:
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./Cuarzo_Browser*.AppImage https://transfer.sh/Cuarzo_Browser-git.$(git rev-parse --short HEAD)-x86_64.AppImage
