language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base qt59webengine qt59svg qt5-qmake
  - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - mkdir appdir appdir/usr appdir/usr/bin appdir/usr/share appdir/usr/share/applications
  - cd appdir
  - cp ../cuarzobrowser usr/bin/
  - cp ../cuarzobrowser.desktop .
  - cp ../cuarzobrowser.png cuarzobrowser.png
  - cd ..
  - sudo make DESTDIR=appdir install ; sudo chown -R $USER appdir ; find appdir/

after_success:
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/cuarzobrowser -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/cuarzobrowser -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - ls -lh ./Cuarzo_Browser*.AppImage
  - mv ./Cuarzo_Browser*.AppImage CuarzoBrowser-continuous-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh CuarzoBrowser-continuous-x86_64.AppImage

branches:
  except:
    - #Do not build manually uploaded files to Github Releases
    - /^(?i:continuous)$/
